# Compile results of RF optimization

# load packages
require(tidyverse)
require(httr)
require(rvest)

#-------------------------------------------------
# Results were generated by 100 super-computers (thanks to Robert), and stored at 'https://geodata.ucdavis.edu/fsa/RFoptim'

# --------------------------------------------------
# List of model outputs (.rds files)
rf_models <- rvest::read_html('https://geodata.ucdavis.edu/fsa/RFoptim') |>
  rvest::html_nodes('a') |>
  rvest::html_attr('href')
model_output <- rf_models[grepl('\\.rds$', rf_models, ignore.case = T)]

# Function to extract the result table from any valid model output
summarize_rfoptim <- function(filename){
  url <- paste0('https://geodata.ucdavis.edu/fsa/RFoptim/', filename)
  temp_file <- tempfile(fileext = ".rds")
  httr::GET(url, write_disk(temp_file, overwrite = T))
  out <- readRDS(temp_file)
  one_row <- cbind(filename = filename, out$results)
  return(one_row)
}

# Table of all results
all_rf_result_table <- do.call(rbind, lapply(model_output, summarize_rfoptim))
all_rf_result_table <- all_rf_result_table |>
  arrange(-Rsquared, RMSE, MAE)
saveRDS(all_rf_result_table, '../output/tables/RF_optim_summarized_table.rds')
write.csv(all_rf_result_table, file = '../output/tables/RF_optim_summarized_table.csv', row.names = F)